Repository Fagyesz/Carpe-Diem, pull requests merged in 2023-04, with the labels that each got.

#87 8. Create event form
  Carpe-Diem/app/Http/Controllers/EventController.php
  Carpe-Diem/app/Models/Event.php
  Carpe-Diem/database/migrations/2023_03_30_151408_create_events_table.php
  Carpe-Diem/resources/views/components/card.blade.php
  Carpe-Diem/resources/views/components/flash-message.blade.php
  Carpe-Diem/resources/views/events/create.blade.php
  Carpe-Diem/routes/web.php
Labels: Difficulty-Easy, frontend

#90 6 implement the login page with email and password fields
  Carpe-Diem/app/Http/Controllers/LoginController.php
  Carpe-Diem/public/main.css
  Carpe-Diem/resources/views/login.blade.php
  Carpe-Diem/routes/web.php
Labels: Difficulty-Easy, frontend

#88 7 Creating the home page basic layout
  Carpe-Diem/app/Http/Controllers/EventController.php
  Carpe-Diem/app/Models/Event.php
  Carpe-Diem/public/images/calendar_logo.png
  Carpe-Diem/public/images/laravel_logo.png
  Carpe-Diem/public/images/no_image.png
  Carpe-Diem/resources/views/event.blade.php
  Carpe-Diem/resources/views/events.blade.php
  Carpe-Diem/resources/views/events/index.blade.php
  Carpe-Diem/resources/views/layout.blade.php
  Carpe-Diem/resources/views/partials/hero.blade.php
  Carpe-Diem/resources/views/partials/search.blade.php
  Carpe-Diem/resources/views/welcome.blade.php
  Carpe-Diem/routes/web.php
Labels: Difficulty-Medium, frontend

#140 113 implement image handling for the database to allow users to upload images for events or their profiles
  Carpe-Diem/app/Http/Controllers/Auth/RegisterController.php
  Carpe-Diem/app/Http/Controllers/EventController.php
  Carpe-Diem/app/Models/Event.php
  Carpe-Diem/config/filesystems.php
  Carpe-Diem/database/migrations/2023_03_27_124914_create_Event_table.php
  Carpe-Diem/resources/views/auth/register.blade.php
  Carpe-Diem/resources/views/events/create.blade.php
Labels: Difficulty-Easy, frontend, database

#141 120 create an event list page that displays all events
  Carpe-Diem/app/Http/Controllers/EventController.php
  Carpe-Diem/app/Models/Event.php
  Carpe-Diem/public/images/no_image.jpg
  Carpe-Diem/public/images/no_image.png
  Carpe-Diem/resources/views/components/card.blade.php
  Carpe-Diem/resources/views/components/event-card.blade.php
  Carpe-Diem/resources/views/events/events_listing.blade.php
  Carpe-Diem/resources/views/partials/hero.blade.php
  Carpe-Diem/resources/views/partials/search.blade.php
  Carpe-Diem/routes/web.php
Labels: Difficulty-Medium, frontend

#144 107 create an event page for every event where we display it as a card with its details
  Carpe-Diem/app/Http/Controllers/EventController.php
  Carpe-Diem/public/images/single_listing_bg.jpg
  Carpe-Diem/resources/views/components/card.blade.php
  Carpe-Diem/resources/views/components/event-card.blade.php
  Carpe-Diem/resources/views/events/create.blade.php
  Carpe-Diem/resources/views/events/show.blade.php
  Carpe-Diem/routes/web.php
Labels: Difficulty-Medium, frontend

#146 145 create an edit/delete form on the listed events
  Carpe-Diem/app/Http/Controllers/EventController.php
  Carpe-Diem/resources/views/events/edit.blade.php
  Carpe-Diem/routes/web.php
Labels: Difficulty-Medium, backend, database

#151 110 create a contact page with a submit form that allows users to send messages to the website administrator
  Carpe-Diem/app/Http/Controllers/ContactController.php
  Carpe-Diem/app/Mail/ContactMail.php
  Carpe-Diem/package.json
  Carpe-Diem/public/images/contact_page.jpg
  Carpe-Diem/resources/views/emails/contactPage.blade.php
  Carpe-Diem/resources/views/emails/email.blade.php
  Carpe-Diem/routes/web.php
Labels: Difficulty-Medium, backend

#153 152 fixing up the event listing page css to a better looking one that wont cause eye cancer instantly hopefully
  Carpe-Diem/public/images/events_page.jpg
  Carpe-Diem/resources/views/components/event-card.blade.php
  Carpe-Diem/resources/views/events/events_listing.blade.php
  Carpe-Diem/routes/web.php
Labels: Difficulty-Medium, frontend

#155 Only the same event organizer can...
  Carpe-Diem/resources/views/events/show.blade.php
Labels: Difficulty-Easy, backend

#157 feat(API) API for search
  Carpe-Diem/app/Http/Controllers/API.php
  Carpe-Diem/routes/api.php
Labels: backend

#168 163 make personal test report dn3opw
  docs/tests/Test_DN3OPW.md
Labels: documentation, testing

#171 160 make personal test report c901ee
  docs/tests/Test_Report-C901EE.md
Labels: documentation, backend, testing

#172 164 make validations throughout the project check if the data has the correct type and value
  Carpe-Diem/app/Http/Controllers/ContactController.php
  Carpe-Diem/app/Http/Controllers/EventController.php
Labels: Difficulty-Easy, backend, testing

#176 create new document
  docs/tests/test_B3P4H0.md
Labels: documentation, testing

#177 feat(API) API for comments
  Carpe-Diem/app/Http/Controllers/API.php
  Carpe-Diem/routes/api.php
Labels: backend

#178 feat(API) Api for posts
  Carpe-Diem/app/Http/Controllers/API.php
  Carpe-Diem/routes/api.php
Labels: backend

#179 170 improve the website design
  Carpe-Diem/public/images/login_register_page.jpg
  Carpe-Diem/resources/views/auth/login.blade.php
  Carpe-Diem/resources/views/auth/register.blade.php
  Carpe-Diem/resources/views/layout.blade.php
  Carpe-Diem/resources/views/partials/hero.blade.php
Labels: Difficulty-Medium, frontend

#158 108 create a user profile page that displays user information and allows users to edit their profile
  Carpe-Diem/app/Http/Controllers/Auth/RegisterController.php
  Carpe-Diem/app/Http/Controllers/UserController.php
  Carpe-Diem/public/images/avatar_placeholder.png
  Carpe-Diem/resources/views/auth/editProfile.blade.php
  Carpe-Diem/resources/views/auth/profile.blade.php
  Carpe-Diem/resources/views/auth/register.blade.php
  Carpe-Diem/resources/views/components/card.blade.php
  Carpe-Diem/resources/views/events/edit.blade.php
  Carpe-Diem/resources/views/layout.blade.php
  Carpe-Diem/routes/web.php
Labels: Difficulty-Medium, frontend

#180 fix(API) Minor fixes for apis
  Carpe-Diem/app/Http/Controllers/API.php
Labels: backend

#183 162 finishing the profile page based on the bought tickets and sold tickets 1
  Carpe-Diem/app/Http/Controllers/EventController.php
  Carpe-Diem/app/Http/Controllers/UserController.php
  Carpe-Diem/resources/views/auth/profile.blade.php
Labels: backend

#184 165 make possible to buy multiple tickets at once
  Carpe-Diem/app/Http/Controllers/QrCodeController.php
  Carpe-Diem/resources/views/events/show.blade.php
Labels: Difficulty-Easy, backend
