Repository Fagyesz/Carpe-Diem, pull requests merged in 2023-05, with the labels that each got.

#186 117 add cypress for automated testing to ensure the functionality of the website
  Carpe-Diem/.env.cypress
  Carpe-Diem/app/Http/Controllers/Auth/RegisterController.php
  Carpe-Diem/app/Http/Controllers/EventController.php
  Carpe-Diem/app/Http/Controllers/UserController.php
  Carpe-Diem/composer.json
  Carpe-Diem/composer.lock
  Carpe-Diem/cypress.config.js
  Carpe-Diem/database/factories/UserFactory.php
  Carpe-Diem/package-lock.json
  Carpe-Diem/package.json
  Carpe-Diem/public/images/create_event.jpg
  Carpe-Diem/resources/views/auth/editProfile.blade.php
  Carpe-Diem/resources/views/events/create.blade.php
  Carpe-Diem/tests/cypress/integration/auth_spec.cy.js
  Carpe-Diem/tests/cypress/integration/contact.cy.js
  Carpe-Diem/tests/cypress/integration/create_event.cy.js
  Carpe-Diem/tests/cypress/integration/edit_event.cy.js
  Carpe-Diem/tests/cypress/integration/profile_edit.cy.js
  Carpe-Diem/tests/cypress/plugins/index.js
  Carpe-Diem/tests/cypress/plugins/swap-env.js
  Carpe-Diem/tests/cypress/support/assertions.js
  Carpe-Diem/tests/cypress/support/index.d.ts
  Carpe-Diem/tests/cypress/support/index.js
  Carpe-Diem/tests/cypress/support/laravel-commands.js
  Carpe-Diem/tests/cypress/support/laravel-routes.js
  Carpe-Diem/tests/cypress/support/routes.json
Labels: Difficulty-Hard, backend

#192 181 improve the navigation bar
  Carpe-Diem/public/images/default_background.jpg
  Carpe-Diem/resources/views/auth/profile.blade.php
  Carpe-Diem/resources/views/components/navbar.blade.php
  Carpe-Diem/resources/views/emails/contactPage.blade.php
  Carpe-Diem/resources/views/layout.blade.php
  Carpe-Diem/resources/views/partials/hero.blade.php
  Carpe-Diem/resources/views/partials/search.blade.php
Labels: Difficulty-Medium, frontend

#193 182 go live design upgrade for the website 1
  Carpe-Diem/resources/views/components/navbar.blade.php
  Carpe-Diem/resources/views/events/index.blade.php
  Carpe-Diem/resources/views/partials/footer.blade.php
  Carpe-Diem/resources/views/partials/hero.blade.php
Labels: Difficulty-Medium, frontend

#194 13 design and implement responsive layouts for mobile devices
  Carpe-Diem/resources/views/auth/editProfile.blade.php
  Carpe-Diem/resources/views/auth/login.blade.php
  Carpe-Diem/resources/views/auth/profile.blade.php
  Carpe-Diem/resources/views/auth/register.blade.php
  Carpe-Diem/resources/views/components/navbar.blade.php
  Carpe-Diem/resources/views/emails/contactPage.blade.php
  Carpe-Diem/resources/views/events/edit.blade.php
  Carpe-Diem/resources/views/events/events_listing.blade.php
  Carpe-Diem/resources/views/events/show.blade.php
  Carpe-Diem/resources/views/partials/footer.blade.php
  Carpe-Diem/resources/views/partials/search.blade.php
Labels: Difficulty-Medium, frontend

#195 Fix(minor) fixes for APIs
  Carpe-Diem/app/Http/Controllers/API.php
Labels: backend
